const insert = document.getElementById('insert');   //we can also use (querySelector) instead of (getElementById) it will give same result

window.addEventListener('keydown',(e) => {      //(window) represent whole browser window   //(keydown) events happen anywhere in the page, as long as the window is focused.
    insert.innerHTML = `
        
        <table>
    <tr>
      <th>Key</th>
      <th>Keycode</th> 
      <th>Code</th>
    </tr>
    <tr>
      <td>${e.key === ' ' ? 'Space' : e.key}</td>
      <td>${e.keyCode}</td> 
      <td>${e.code}</td>       


    </tr>
    
  </table>
       
    `;
});


//THIS CODE IS GENERATED BY ME:
    // window.addEventListener('keydown',(e) => {
    //     insert.innerHTML = `KeyPressed: <b>${e.key}</b>,<br> KeyCode: <b>${e.keyCode}</b>,<br> Key: <b>${e.code}</b>`;
    // });





/* INFO:
1).code
    Represents the physical key on the keyboard, independent of modifiers.
    It doesn’t change with Shift or Caps Lock.

2).key
    Represents the character produced by the key press, taking modifiers into account (Shift, Caps Lock, etc.).

3).keyCode
    It returns a number representing the key that was pressed.
*/